source 'https://github.com/CocoaPods/Specs'

platform :ios, '12.0'

use_frameworks!

xcodeproj 'LUAutocompleteViewExample'
workspace '../LUAutocompleteView'

target :LUAutocompleteViewExample do
  pod 'LUAutocompleteView', :path => '../'

end
